GET https://us-central1-socialapp-7aba4.cloudfunctions.net/api/screams 

###

POST  https://us-central1-socialapp-7aba4.cloudfunctions.net/api/login
Content-Type: application/json

{
    "email":"bhavin@gmail.com",
    "password":"123456"
}

###
GET   https://us-central1-socialapp-7aba4.cloudfunctions.net/api/scream/PpTlnSfqnD8KKOUb77rI/like
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLTdhYmE0IiwiYXVkIjoic29jaWFsYXBwLTdhYmE0IiwiYXV0aF90aW1lIjoxNTg3ODMyNjk2LCJ1c2VyX2lkIjoiY1JkMlNMeHVSYlo2SGkwdFFXdUMxOUY1Tm12MSIsInN1YiI6ImNSZDJTTHh1UmJaNkhpMHRRV3VDMTlGNU5tdjEiLCJpYXQiOjE1ODc4MzI2OTYsImV4cCI6MTU4NzgzNjI5NiwiZW1haWwiOiJiaGF2aW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImJoYXZpbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.QlHPoLFyk7HEkABfFFLy26Go1pWXu0OckkXJNq6D3ncwiD9cj5MEmW9d1d0tyhefudhBs53kKxcw7r_R5-FOvn_v5xbTIOILV7ZSoElY7zaUvK9o3s1y5vZuUQe-bC2OQGRN2m7agBpjzCEBq3PMYZIbZycIcb9UDdr9rvEZqgU0SrClG_SMtdsTyOJNTTZlseyt1bZLSNNotFDTqRqMTRzF3pw203S1LYksS4jerwBDcKg8vz4R6mDersQt7W2x7bix7OQfTMJbZ1_U-DWLo8zfu4Ug0QGDqckWU4TwN4c6qO-Zu2bydE0wBCOwSqAcwxkz9xw2J8KrTjMW0le0vw 


###
DELETE https://us-central1-socialapp-7aba4.cloudfunctions.net/api/scream/PpTlnSfqnD8KKOUb77rI
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLTdhYmE0IiwiYXVkIjoic29jaWFsYXBwLTdhYmE0IiwiYXV0aF90aW1lIjoxNTg3ODMyNjk2LCJ1c2VyX2lkIjoiY1JkMlNMeHVSYlo2SGkwdFFXdUMxOUY1Tm12MSIsInN1YiI6ImNSZDJTTHh1UmJaNkhpMHRRV3VDMTlGNU5tdjEiLCJpYXQiOjE1ODc4MzI2OTYsImV4cCI6MTU4NzgzNjI5NiwiZW1haWwiOiJiaGF2aW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImJoYXZpbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.QlHPoLFyk7HEkABfFFLy26Go1pWXu0OckkXJNq6D3ncwiD9cj5MEmW9d1d0tyhefudhBs53kKxcw7r_R5-FOvn_v5xbTIOILV7ZSoElY7zaUvK9o3s1y5vZuUQe-bC2OQGRN2m7agBpjzCEBq3PMYZIbZycIcb9UDdr9rvEZqgU0SrClG_SMtdsTyOJNTTZlseyt1bZLSNNotFDTqRqMTRzF3pw203S1LYksS4jerwBDcKg8vz4R6mDersQt7W2x7bix7OQfTMJbZ1_U-DWLo8zfu4Ug0QGDqckWU4TwN4c6qO-Zu2bydE0wBCOwSqAcwxkz9xw2J8KrTjMW0le0vw